version: '3.8'

services:
  db:
    image: postgres:13-alpine
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
  
  adminer:
    image: adminer
    container_name: adminer_gui
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - db

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge